include:
  - project: 'cjexpress/posback/pipeline'
    ref: develop
    file: reactwithsonar-k8s-pipeline.yml

variables:
  PROJECT_NAME: cj-pos-back-web
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
