export const mockStoreSearchCloseSaleShift = {
  authorizedhBranchSlice: {
    branchList: {
      timestamp: '2022-06-16T02:56:55.558+0000',
      ref: '62aa9bf7a366e4b9291084a1',
      code: 20000,
      message: 'success',
      data: {
        branches: [
          {
            code: '0101',
            name: 'สาขาที่00123 ไทรโยค',
            isDC: false,
          },
          {
            code: '0799',
            name: 'สาขาที่0799 ห้วยราช',
            isDC: false,
          },
          {
            code: '0722',
            name: 'สาขาที่00000 ตลาดทุ่งโพธิ์',
            isDC: false,
          },
          {
            code: 'D002',
            name: 'สาขาที่00575 ศูนย์กระจายสินค้า คลัง 2',
            isDC: true,
          },
        ],
      },
    },
    error: '',
  },
  searchBranchSlice: {
    branchList: {
      ref: '62aa9bf7573d5f20455eb5a6',
      code: 20000,
      message: 'success',
      data: [
        {
          id: '61dffd799bfc3701dce4f0f5',
          name: 'CJค้าส่งบ้านเลือก',
          province: {
            code: 0,
            name: '',
          },
          code: 'B004',
          isDC: false,
        },
        {
          id: '61dffd799bfc3701dce4f0fa',
          name: 'Nineti9(Online)',
          province: {
            code: 0,
            name: '',
          },
          code: 'B009',
          isDC: false,
        },
        {
          id: '61dffd799bfc3701dce4f287',
          name: 'สาขาที่00253 ตลาดโพธาราม',
          province: {
            code: 52,
            name: 'ราชบุรี',
          },
          code: '0239',
          isDC: false,
        },
      ],
    },
  },
  closeSaleShiftSlice: {
    closeSaleShift: {
      timestamp: '2022-08-11T03:30:12.054+0000',
      ref: '62f477c4591c5cfe9a49c46b',
      code: 20000,
      message: 'success',
      data: [
        {
          branchCode: '0101',
          shiftCode: '20220811T03-001',
          shiftDate: '2022-08-11T02:46:39.301Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: 'T03',
          posUser: 'pangpos',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811012-001',
          shiftDate: '2022-08-11T03:01:27.566Z',
          shiftAmount: 2065,
          billAmount: 2065,
          confirmAmount: null,
          noOfSaleBill: 4,
          noOfReturnBill: 1,
          status: 'DRAFT',
          posCode: '012',
          posUser: 'nungning',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811012-002',
          shiftDate: '2022-08-11T03:04:39.841Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '012',
          posUser: 'ning',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811070-001',
          shiftDate: '2022-08-11T03:11:19.989Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '070',
          posUser: 'tuck',
        },
        {
          branchCode: '0101',
          shiftCode: '20220810068-001',
          shiftDate: '2022-08-11T03:42:34.97Z',
          shiftAmount: 100,
          billAmount: 100,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '068',
          posUser: 'jickabyte',
        },
        {
          branchCode: '0101',
          shiftCode: '20220801T05-021',
          shiftKey: '186A00',
          shiftDate: '2022-08-11T10:28:20.844Z',
          shiftAmount: 1000,
          billAmount: 1000,
          confirmAmount: 1000,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: 'T05',
          posUser: 'boy-m',
        },
      ],
      total: 6,
      page: 1,
      perPage: 10,
      totalPage: 1,
    },
    error: '',
    payloadSearch: {
      shiftDate: '2022-08-11T16:59:59.999Z',
      branchCode: '0101',
      status: 'ALL',
      page: 1,
      limit: 10,
    },
  },
  searchCashStatement: {
    cashStatementList: {
      ref: '',
      code: 0,
      message: '',
      data: [],
      total: 0,
      page: 0,
      perPage: 0,
      prev: 0,
      next: 0,
      totalPage: 0,
    },
    error: '',
  },
  saveCashStatementSearchRequest: {
    searchCashStatement: {
      limit: '10',
      page: '1',
      status: '',
      branchCode: '',
      dateFrom: '',
      dateTo: '',
    },
  },
  searchOpenEndSlice: {
    openEndSearchList: {
      timestamp: '',
      ref: '',
      code: 0,
      message: '',
      data: [],
      total: 0,
      page: 0,
      perPage: 0,
      prev: 0,
      next: 0,
      totalPage: 0,
    },
    error: '',
    payloadOpenEndSearch: {
      limit: '10',
      page: '1',
      status: '',
      branchCode: '',
      dateFrom: '',
      dateTo: '',
    },
  },
  viewOpenEndSlice: {
    viewOpenEnd: {
      timestamp: '',
      ref: '',
      code: 0,
      message: '',
      data: null,
    },
    error: '',
  },
};

export const mockStoreSearchCloseSaleShiftMoreTenRecords = {
  authorizedhBranchSlice: {
    branchList: {
      timestamp: '2022-06-16T02:56:55.558+0000',
      ref: '62aa9bf7a366e4b9291084a1',
      code: 20000,
      message: 'success',
      data: {
        branches: [
          {
            code: '0101',
            name: 'สาขาที่00123 ไทรโยค',
            isDC: false,
          },
          {
            code: '0799',
            name: 'สาขาที่0799 ห้วยราช',
            isDC: false,
          },
          {
            code: '0722',
            name: 'สาขาที่00000 ตลาดทุ่งโพธิ์',
            isDC: false,
          },
          {
            code: 'D002',
            name: 'สาขาที่00575 ศูนย์กระจายสินค้า คลัง 2',
            isDC: true,
          },
        ],
      },
    },
    error: '',
  },
  searchBranchSlice: {
    branchList: {
      ref: '62aa9bf7573d5f20455eb5a6',
      code: 20000,
      message: 'success',
      data: [
        {
          id: '61dffd799bfc3701dce4f0f5',
          name: 'CJค้าส่งบ้านเลือก',
          province: {
            code: 0,
            name: '',
          },
          code: 'B004',
          isDC: false,
        },
        {
          id: '61dffd799bfc3701dce4f0fa',
          name: 'Nineti9(Online)',
          province: {
            code: 0,
            name: '',
          },
          code: 'B009',
          isDC: false,
        },
        {
          id: '61dffd799bfc3701dce4f287',
          name: 'สาขาที่00253 ตลาดโพธาราม',
          province: {
            code: 52,
            name: 'ราชบุรี',
          },
          code: '0239',
          isDC: false,
        },
      ],
    },
  },
  closeSaleShiftSlice: {
    closeSaleShift: {
      timestamp: '2022-08-11T03:30:12.054+0000',
      ref: '62f477c4591c5cfe9a49c46b',
      code: 20000,
      message: 'success',
      data: [
        {
          branchCode: '0101',
          shiftCode: '20220811T03-001',
          shiftDate: '2022-08-11T02:46:39.301Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: 'T03',
          posUser: 'pangpos',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811012-001',
          shiftDate: '2022-08-11T03:01:27.566Z',
          shiftAmount: 2065,
          billAmount: 2065,
          confirmAmount: null,
          noOfSaleBill: 4,
          noOfReturnBill: 1,
          status: 'DRAFT',
          posCode: '012',
          posUser: 'nungning',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811012-002',
          shiftDate: '2022-08-11T03:04:39.841Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '012',
          posUser: 'ning',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811070-001',
          shiftDate: '2022-08-11T03:11:19.989Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '070',
          posUser: 'tuck',
        },
        {
          branchCode: '0101',
          shiftCode: '20220810068-001',
          shiftDate: '2022-08-11T03:42:34.97Z',
          shiftAmount: 100,
          billAmount: 100,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '068',
          posUser: 'jickabyte',
        },
        {
          branchCode: '0101',
          shiftCode: '20220801T05-021',
          shiftKey: '186A00',
          shiftDate: '2022-08-11T10:28:20.844Z',
          shiftAmount: 1000,
          billAmount: 1000,
          confirmAmount: 1000,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'CORRECT',
          posCode: 'T05',
          posUser: 'boy-m',
        },

        {
          branchCode: '0101',
          shiftCode: '20220811T03-0012',
          shiftDate: '2022-08-11T02:46:39.301Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: null,
          noOfReturnBill: null,
          status: 'PENDING_REVIEW',
          posCode: 'T03',
          posUser: 'pangpos',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811012-0012',
          shiftDate: '2022-08-11T03:01:27.566Z',
          shiftAmount: 2060,
          billAmount: 2065,
          confirmAmount: null,
          noOfSaleBill: 4,
          noOfReturnBill: 1,
          status: 'DRAFT',
          posCode: '012',
          posUser: 'nungning',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811012-0022',
          shiftDate: '2022-08-11T03:04:39.841Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '012',
          posUser: 'ning',
        },
        {
          branchCode: '0101',
          shiftCode: '20220811070-0012',
          shiftDate: '2022-08-11T03:11:19.989Z',
          shiftAmount: null,
          billAmount: null,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '070',
          posUser: 'tuck',
        },
        {
          branchCode: '0101',
          shiftCode: '20220810068-0012',
          shiftDate: '2022-08-11T03:42:34.97Z',
          shiftAmount: 200,
          billAmount: 100,
          confirmAmount: null,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'DRAFT',
          posCode: '068',
          posUser: 'jickabyte',
        },
        {
          branchCode: '0101',
          shiftCode: '20220801T05-0212',
          shiftKey: '186A00',
          shiftDate: '2022-08-11T10:28:20.844Z',
          shiftAmount: 1000,
          billAmount: 1000,
          confirmAmount: 1000,
          noOfSaleBill: 0,
          noOfReturnBill: 0,
          status: 'PENDING_REVIEW',
          posCode: 'T05',
          posUser: 'boy-m',
        },
      ],
      total: 12,
      page: 1,
      perPage: 10,
      totalPage: 2,
    },
    error: '',
    payloadSearch: {
      shiftDate: '2022-08-11T16:59:59.999Z',
      branchCode: '0101',
      status: 'ALL',
      page: 1,
      limit: 10,
    },
  },
  searchCashStatement: {
    cashStatementList: {
      ref: '',
      code: 0,
      message: '',
      data: [],
      total: 0,
      page: 0,
      perPage: 0,
      prev: 0,
      next: 0,
      totalPage: 0,
    },
    error: '',
  },
  saveCashStatementSearchRequest: {
    searchCashStatement: {
      limit: '10',
      page: '1',
      status: '',
      branchCode: '',
      dateFrom: '',
      dateTo: '',
    },
  },
  searchOpenEndSlice: {
    openEndSearchList: {
      timestamp: '',
      ref: '',
      code: 0,
      message: '',
      data: [],
      total: 0,
      page: 0,
      perPage: 0,
      prev: 0,
      next: 0,
      totalPage: 0,
    },
    error: '',
    payloadOpenEndSearch: {
      limit: '10',
      page: '1',
      status: '',
      branchCode: '',
      dateFrom: '',
      dateTo: '',
    },
  },
  viewOpenEndSlice: {
    viewOpenEnd: {
      timestamp: '',
      ref: '',
      code: 0,
      message: '',
      data: null,
    },
    error: '',
  },
};
export const mockStoreSearchCloseSaleShiftNoData = {
  authorizedhBranchSlice: {
    branchList: {
      timestamp: '2022-06-16T02:56:55.558+0000',
      ref: '62aa9bf7a366e4b9291084a1',
      code: 20000,
      message: 'success',
      data: {
        branches: [
          {
            code: '0101',
            name: 'สาขาที่00123 ไทรโยค',
            isDC: false,
          },
          {
            code: '0799',
            name: 'สาขาที่0799 ห้วยราช',
            isDC: false,
          },
          {
            code: '0722',
            name: 'สาขาที่00000 ตลาดทุ่งโพธิ์',
            isDC: false,
          },
          {
            code: 'D002',
            name: 'สาขาที่00575 ศูนย์กระจายสินค้า คลัง 2',
            isDC: true,
          },
        ],
      },
    },
    error: '',
  },
  searchBranchSlice: {
    branchList: {
      ref: '62aa9bf7573d5f20455eb5a6',
      code: 20000,
      message: 'success',
      data: [
        {
          id: '61dffd799bfc3701dce4f0f5',
          name: 'CJค้าส่งบ้านเลือก',
          province: {
            code: 0,
            name: '',
          },
          code: 'B004',
          isDC: false,
        },
        {
          id: '61dffd799bfc3701dce4f0fa',
          name: 'Nineti9(Online)',
          province: {
            code: 0,
            name: '',
          },
          code: 'B009',
          isDC: false,
        },
        {
          id: '61dffd799bfc3701dce4f287',
          name: 'สาขาที่00253 ตลาดโพธาราม',
          province: {
            code: 52,
            name: 'ราชบุรี',
          },
          code: '0239',
          isDC: false,
        },
      ],
    },
  },
  closeSaleShiftSlice: {
    closeSaleShift: {
      timestamp: '2022-08-11T03:30:12.054+0000',
      ref: '62f477c4591c5cfe9a49c46b',
      code: 20000,
      message: 'success',
      data: [],
      total: 6,
      page: 1,
      perPage: 10,
      totalPage: 1,
    },
    error: '',
    payloadSearch: {
      shiftDate: '2022-08-11T16:59:59.999Z',
      branchCode: '0101',
      status: 'ALL',
      page: 1,
      limit: 10,
    },
  },
  searchCashStatement: {
    cashStatementList: {
      ref: '',
      code: 0,
      message: '',
      data: [],
      total: 0,
      page: 0,
      perPage: 0,
      prev: 0,
      next: 0,
      totalPage: 0,
    },
    error: '',
  },
  saveCashStatementSearchRequest: {
    searchCashStatement: {
      limit: '10',
      page: '1',
      status: '',
      branchCode: '',
      dateFrom: '',
      dateTo: '',
    },
  },
  searchOpenEndSlice: {
    openEndSearchList: {
      timestamp: '',
      ref: '',
      code: 0,
      message: '',
      data: [],
      total: 0,
      page: 0,
      perPage: 0,
      prev: 0,
      next: 0,
      totalPage: 0,
    },
    error: '',
    payloadOpenEndSearch: {
      limit: '10',
      page: '1',
      status: '',
      branchCode: '',
      dateFrom: '',
      dateTo: '',
    },
  },
  viewOpenEndSlice: {
    viewOpenEnd: {
      timestamp: '',
      ref: '',
      code: 0,
      message: '',
      data: null,
    },
    error: '',
  },
};
