export interface StockTransferRequest {
  limit: string;
  page: string;
  docNo?: string;
  branchFrom: string;
  branchTo: string;
  dateFrom?: string;
  dateTo?: string;
  statuses?: string;
  transferReason?: string;
  clearSearch?: boolean;
}
export interface StockTransferResponse {
  ref: string;
  code: number;
  message: string;
  data: StockTransferInfo[];
  total: number;
  page: number;
  perPage: number;
  prev: number;
  next: number;
  totalPage: number;
}

export interface StockTransferInfo {
  id: string;
  btNo: string;
  rtNo: string;
  sdNo: string;
  startDate: string;
  endDate: string;
  branchFrom: string;
  branchFromName: string;
  branchTo: string;
  branchToName: string;
  transferReason: string;
  createdBy: string;
  lastModifiedBy: string;
  createdDate: string;
  lastModifiedDate: string;
  status: string;
}
export interface SaveStockTransferRequest {
  btNo: string;
  sdNo: string;
  startDate: string;
  endDate: string;
  branchFrom: string;
  branchTo: string;
  transferReason: string;
  items: StockTransferItems[];
}

export interface StockTransferItems {
  barcode?: string;
  skuCode?: string;
  productName?: string;
  baseUnit?: string;
  unitCode?: string;
  unitName?: string;
  orderQty?: number;
  orderAllQty?: number;
  toleNo?: string;
}

export interface SaveStockPackRequest {
  btNo?: string;
  sdNo?: string;
  startDate?: string;
  endDate?: string;
  comment?: string;
  items?: StockTransferItems[];
}


// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Untitled1 {
  timestamp: string;
  ref:       string;
  code:      number;
  message:   string;
  data:      Data;
}

export interface Data {
  id:               string;
  btNo:             string;
  branchCode:       string;
  startDate:        string;
  endDate:          string;
  branchFrom:       string;
  branchTo:         string;
  items:            Item[];
  status:           string;
  auditLogs:        AuditLog[];
  createdBy:        string;
  lastModifiedBy:   string;
  createdDate:      string;
  lastModifiedDate: string;
}

export interface AuditLog {
  activity:   string;
  editBy:     string;
  editByName: string;
  editDate:   string;
}

export interface Item {
  skuCode:     string;
  barcode:     string;
  productName: string;
  unitCode:    string;
  unitName:    string;
  orderQty:    number;
  orderAllQty: number;
}


